### ISSUE TITLE
engine client sid issue

### ISSUE THREAD

**Issue by manishiitg** [pion/ion-sdk-go#37]
### Your environment.
  - Version: *Release or SHA*
  - Browser: *include version*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?

when we create new client using sdk.NewClient, it automatically adds the client to engline but at this stage there no sid assigned to the client.  

the clients map in engine has all nil keys? 

Add client should be done on Join() instead when creating new client?

https://github.com/pion/ion-sdk-go/blob/26d31be8c6027b86740a34f12838c053b1270abd/client.go#L78
https://github.com/pion/ion-sdk-go/blob/master/engine.go#L43

**Comment by adwpc** [comment]
new version del engine.
move to ion-sfu load tool
