### ISSUE TITLE
Custom OnTrack not triggered

### ISSUE THREAD

**Issue by tomsun** [pion/ion-sdk-go#4]
`Client.OnTrack` exists in the interface
https://github.com/pion/ion-sdk-go/blob/5d08b8a039c64d301d42ca93d345e612ea90a6ab/client.go#L34-L35

...but looks like the intended trigger is commented here:
https://github.com/pion/ion-sdk-go/blob/5d08b8a039c64d301d42ca93d345e612ea90a6ab/client.go#L135-L137

Plans to enable it?

**Comment by adwpc** [comment]
Yes
we can

**Comment by tomsun** [comment]
Nice, thank you @adwpc !
