### ISSUE TITLE
ion-sfu-gstreamer-receive sample does not work

### ISSUE THREAD

**Issue by impleotv** [pion/ion-sdk-go#45]
Command (as in the instructions): 
go get github.com/pion/ion-sdk-go/example/ion-sfu-gstreamer-receive  

Result: 
github.com/pion/ion-sdk-go/example/ion-sfu-gstreamer-receive
./main.go:39:3: unknown field 'Log' in struct literal of type engine.Config

Thanks,

Alex

**Comment by TannerGabriel** [comment]
This seems to be an issue since the `sdk.Config` changed with the new `ion-sdk-go` version and therefore the parameters that need to be passed are different. Removing the log from the parameters should fix your issue:

```
config := sdk.Config{
  WebRTC: sdk.WebRTCTransportConfig{
	  Configuration: webrtcCfg,
  },
}
```

**Comment by impleotv** [comment]
Yep. I figured that out. Just wanted to let you know.

Thanks,

Alex
