### ISSUE TITLE
ion-sdk-go@v0.5.0/conf.go:10:6: undefined: "github.com/pion/ion-log"

### ISSUE THREAD

**Issue by knasim** [pion/ion-sdk-go#50]
running one of the examples and I keep getting this ???

../../../../../pkg/mod/github.com/pion/ion-sdk-go@v0.5.0/conf.go:10:6: undefined: "github.com/pion/ion-log".Config
../../../../../pkg/mod/github.com/pion/ion-sdk-go@v0.5.0/ion.go:93:8: undefined: "github.com/pion/ion-log".Config

**Comment by adwpc** [comment]
pls try new version.
